project_id = "cdxdnfysexuvltrjugfc"

[functions.elevenlabs-conversation-token]
verify_jwt = false

[functions.generate-interview-questions]
verify_jwt = false

[functions.analyze-interview]
verify_jwt = false

[functions.send-interview-complete-email]
verify_jwt = false
